In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv ('food_Ingredients.csv')
df.head(10)

,Unnamed: 0,size,calories_kcal,fats_g,sod_mg,carb_g,fiber_g,sugar_g,protein_g,vitA_g,...,vitK_mcg,vitC_mg,vitB6_mg,copper_mg,carotene_mg,carotene_mcg,cryptoxanthin_mcg,lycopene_mcg,cholesterol_mg,quality
0,0,1.0,21.26,0.20,8.79,4.45,0.00,2.69,0.37,0.00,...,0.17,6.95,0.07,0.02,3.40,1.98,1.13,0.0,0.00,1
1,1,NaN,82.49,0.79,2.26,17.40,0.90,11.85,1.47,33.90,...,2.49,24.63,0.23,0.08,14.69,2.26,9.04,0.0,0.00,0
2,2,1.0,20.70,0.20,0.57,4.37,0.23,2.97,0.37,8.51,...,0.62,6.18,0.06,0.02,3.69,0.57,2.27,0.0,0.00,1
3,3,1.0,32.89,1.16,13.04,4.34,0.31,0.00,1.42,29.77,...,0.00,0.37,0.02,0.03,0.00,0.00,0.00,0.0,3.12,3
4,4,1.0,58.95,0.90,17.85,11.01,0.78,2.06,1.80,10.35,...,0.45,0.70,0.06,0.06,4.20,4.05,0.00,0.0,0.00,1
5,5,1.0,55.52,0.99,6.67,9.84,0.00,0.00,1.92,3.27,...,0.00,0.00,0.02,0.08,0.00,0.00,0.00,0.0,0.00,3
6,6,1.0,9.38,0.17,1.13,1.66,0.00,0.00,0.32,0.55,...,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.0,0.00,3
7,7,1.0,9.82,0.15,2.98,1.84,0.13,0.34,0.30,1.72,...,0.08,0.12,0.01,0.01,0.70,0.68,0.00,0.0,0.00,3
8,8,1.0,32.89,1.08,17.29,4.54,0.00,0.00,1.33,28.07,...,0.00,0.45,0.03,0.02,0.00,0.00,0.00,0.0,0.00,3
9,9,1.0,32.60,1.11,13.89,4.34,0.00,0.00,1.42,0.00,...,0.00,0.00,0.02,0.03,0.00,0.00,0.00,0.0,0.00,3

In [7]:
df.isnull().sum()

Unnamed: 0             0
size                 162
calories_kcal          0
fats_g                 0
sod_mg                 0
carb_g                 0
fiber_g                0
sugar_g                0
protein_g              0
vitA_g                 0
calcium_mg             0
thiamin_mg             0
zinc_mg                0
potassium_mg           0
magnesium_mg           0
vitE_mg                0
vitK_mcg               0
vitC_mg                0
vitB6_mg               0
copper_mg              0
carotene_mg            0
carotene_mcg           0
cryptoxanthin_mcg      0
lycopene_mcg           0
cholesterol_mg         0
quality                0
dtype: int64

In [8]:
df.fillna(df.mean(), inplace=True)
df.isnull().sum()

Unnamed: 0           0
size                 0
calories_kcal        0
fats_g               0
sod_mg               0
carb_g               0
fiber_g              0
sugar_g              0
protein_g            0
vitA_g               0
calcium_mg           0
thiamin_mg           0
zinc_mg              0
potassium_mg         0
magnesium_mg         0
vitE_mg              0
vitK_mcg             0
vitC_mg              0
vitB6_mg             0
copper_mg            0
carotene_mg          0
carotene_mcg         0
cryptoxanthin_mcg    0
lycopene_mcg         0
cholesterol_mg       0
quality              0
dtype: int64

In [9]:
df.dtypes

Unnamed: 0             int64
size                 float64
calories_kcal        float64
fats_g               float64
sod_mg               float64
carb_g               float64
fiber_g              float64
sugar_g              float64
protein_g            float64
vitA_g               float64
calcium_mg           float64
thiamin_mg           float64
zinc_mg              float64
potassium_mg         float64
magnesium_mg         float64
vitE_mg              float64
vitK_mcg             float64
vitC_mg              float64
vitB6_mg             float64
copper_mg            float64
carotene_mg          float64
carotene_mcg         float64
cryptoxanthin_mcg    float64
lycopene_mcg         float64
cholesterol_mg       float64
quality                int64
dtype: object

In [12]:
df.astype(int)

,Unnamed: 0,size,calories_kcal,fats_g,sod_mg,carb_g,fiber_g,sugar_g,protein_g,vitA_g,...,vitK_mcg,vitC_mg,vitB6_mg,copper_mg,carotene_mg,carotene_mcg,cryptoxanthin_mcg,lycopene_mcg,cholesterol_mg,quality
0,0,1,21,0,8,4,0,2,0,0,...,0,6,0,0,3,1,1,0,0,1
1,1,2,82,0,2,17,0,11,1,33,...,2,24,0,0,14,2,9,0,0,0
2,2,1,20,0,0,4,0,2,0,8,...,0,6,0,0,3,0,2,0,0,1
3,3,1,32,1,13,4,0,0,1,29,...,0,0,0,0,0,0,0,0,3,3
4,4,1,58,0,17,11,0,2,1,10,...,0,0,0,0,4,4,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,692,6,102,0,37,23,2,7,1,11281,...,2,16,0,0,6769,0,0,0,0,0
692,693,6,102,0,37,23,2,7,1,11281,...,2,16,0,0,6769,0,0,0,0,0
693,694,6,102,0,37,23,2,7,1,11281,...,2,16,0,0,6769,0,0,0,0,0
694,695,1,17,0,6,3,0,1,0,1881,...,0,2,0,0,1128,0,0,0,0,2
695,696,1,8,0,3,1,0,0,0,929,...,0,1,0,0,557,0,0,0,0,3

In [15]:
df = df.apply(pd.to_numeric, errors='coerce').astype(int)

In [16]:
df.dtypes

Unnamed: 0           int32
size                 int32
calories_kcal        int32
fats_g               int32
sod_mg               int32
carb_g               int32
fiber_g              int32
sugar_g              int32
protein_g            int32
vitA_g               int32
calcium_mg           int32
thiamin_mg           int32
zinc_mg              int32
potassium_mg         int32
magnesium_mg         int32
vitE_mg              int32
vitK_mcg             int32
vitC_mg              int32
vitB6_mg             int32
copper_mg            int32
carotene_mg          int32
carotene_mcg         int32
cryptoxanthin_mcg    int32
lycopene_mcg         int32
cholesterol_mg       int32
quality              int32
dtype: object

In [19]:
df.columns

Index(['Unnamed: 0', 'size', 'calories_kcal', 'fats_g', 'sod_mg', 'carb_g',
       'fiber_g', 'sugar_g', 'protein_g', 'vitA_g', 'calcium_mg', 'thiamin_mg',
       'zinc_mg', 'potassium_mg', 'magnesium_mg', 'vitE_mg', 'vitK_mcg',
       'vitC_mg', 'vitB6_mg', 'copper_mg', 'carotene_mg', 'carotene_mcg',
       'cryptoxanthin_mcg', 'lycopene_mcg', 'cholesterol_mg', 'quality'],
      dtype='object')

In [18]:
df.to_csv('cleaned_food(2).csv',index=False)